name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "${{ secrets.EC2_HOST }}"
          username: ec2-user
          key: "${{ secrets.EC2_KEY }}"
          source: "."
          target: "/home/ec2-user/project"

      - name: Build and run Docker on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "${{ secrets.EC2_HOST }}"
          username: ec2-user
          key: "${{ secrets.EC2_KEY }}"
          script: |
            mkdir -p /home/ec2-user/project

            # GitHub Actions runner에서 EC2로 파일 copy
            scp -r $GITHUB_WORKSPACE/* ec2-user@{{ secrets.EC2_HOST }}:/home/ec2-user/project
            
            cd /home/ec2-user/project

            # 기존 컨테이너 제거
            docker stop project || true
            docker rm project || true

            # Docker build & run
            docker build -t project .
            docker run -d -p 80:80 --name project project
