name: CI/CD React to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd my-app
          npm install

      - name: Build React app
        run: |
          cd my-app
          npm run build

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: "${{ secrets.EC2_HOST }}"
          username: ec2-user
          key: "${{ secrets.EC2_SSH_KEY }}"
          source: "my-app/*"
          target: "/home/ec2-user/project/my-app"

      - name: SSH & Deploy Docker
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "${{ secrets.EC2_HOST }}"
          username: ec2-user
          key: "${{ secrets.EC2_SSH_KEY }}"
          script: |
            cd /home/ec2-user/project/my-app
            docker build -t react-nginx .
            docker stop react-app || true
            docker rm react-app || true
            docker run -d -p 80:80 -p 443:443 --name react-app react-nginx
